import os
import uuid
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib import colors

def generate_referral_pdf(analysis, risk):
    os.makedirs("outputs", exist_ok=True)
    filename = f"outputs/{uuid.uuid4()}.pdf"
    
    doc = SimpleDocTemplate(
        filename,
        pagesize=letter,
        rightMargin=50,
        leftMargin=50,
        topMargin=50,
        bottomMargin=50
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Styles
    header_style = ParagraphStyle(
        'Header',
        parent=styles['Heading1'],
        alignment=TA_CENTER,
        fontSize=18,
        spaceAfter=6
    )
    
    subheader_style = ParagraphStyle(
        'SubHeader',
        parent=styles['Normal'],
        alignment=TA_CENTER,
        fontSize=10,
        textColor=colors.dimgrey,
        spaceAfter=20
    )
    
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading2'],
        alignment=TA_CENTER,
        fontSize=22,
        spaceAfter=20,
        textColor=colors.black
    )
    
    patient_info_style = ParagraphStyle(
        'PatientInfo',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=15
    )
    
    risk_style = ParagraphStyle(
        'Risk',
        parent=styles['Heading3'],
        fontSize=14,
        textColor=colors.red if "HIGH" in risk.upper() or "EMERGENCY" in risk.upper() else colors.green,
        spaceAfter=15
    )
    
    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontSize=12,
        leading=18,
        spaceAfter=30
    )
    
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=10,
        alignment=TA_RIGHT,
        textColor=colors.dimgrey
    )
    
    elements = []
    
    # Header Section
    elements.append(Paragraph("MATERNAL HEALTH AI", header_style))
    elements.append(Paragraph("Automated Triage & Assessment System", subheader_style))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.black, spaceAfter=20))
    
    # Title
    elements.append(Paragraph("PRELIMINARY ASSESSMENT", title_style))
    
    # Date & Basic Info
    current_date = datetime.now().strftime("%B %d, %Y - %I:%M %p")
    elements.append(Paragraph(f"<b>Date:</b> {current_date}", patient_info_style))
    elements.append(Paragraph(f"<b>Patient Name:</b> ____________________ &nbsp;&nbsp;&nbsp;&nbsp; <b>Age / Sex:</b> ___ / F", patient_info_style))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey, spaceAfter=20))
    
    # Risk Assessment
    elements.append(Paragraph(f"<b>Diagnosed Risk Level:</b> {risk.upper()}", risk_style))
    
    # AI Findings (Replaces RX section)
    elements.append(Paragraph("<b><u>AI Clinical Findings & Advice:</u></b>", styles['Heading4']))
    
    # Format the analysis text to preserve line breaks if any, or just let it wrap naturally
    clean_analysis = str(analysis).replace('\n', '<br/>')
    elements.append(Paragraph(clean_analysis, body_style))
    
    # Footer & Follow up
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey, spaceAfter=20))
    elements.append(Paragraph("<b>Follow-up:</b> Please consult a qualified doctor immediately for verification.", styles['Normal']))
    elements.append(Spacer(1, 40))
    elements.append(Paragraph("___________________________", footer_style))
    elements.append(Paragraph("Generated by AI Triage System", footer_style))
    
    # Build PDF
    doc.build(elements)
    
    return filename
